baseURL = "https://webdeveloperhints.com/"
DefaultContentLanguage = "es"
languageCode = "es"
title = "Web Developer Hints"
theme = "hugo-dusk"
canonifyurls = true
paginate = 8
enableRobotsTXT = true
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
hasCJKLanguage = false
summaryLength = 80
copyright = "Arturo López © 2020, All Rights Reserved - imágenes gracias a www.freepik.es" # copyright symbol: $copy; current year: {year}
timeout = 10000
enableEmoji = true
rssLimit = 1000
enableGitInfo = true
googleAnalytics = "UA-42486999-5"
disqusShortname = "web-developer-hints"
SectionPagesMenu = "main"
pygmentsStyle = "vim" # other dark style options: vim, fruity, monokai
pygmentsCodeFences = true

[Author]
  name = "Arturo López"

[Params]
  author = "Arturo López"
  description = "Sitio web con artículos sobre desarrollo web, lenguajes de programación y técnicas de programación."
  paginationSinglePost = true
  style = "dark-without-switcher"
  dateFormat = "2006-01-02"
  email = "lgzarturo@gmail.com"
  github = "lgzarturo"
  twitter = "lgzarturo"
  linkedin = "lgzarturo"
  theme_colors = "default-dark"
  utterancesRepo="lgzarturo/webdeveloperhints" # Utterances is enabled when this param is set
  utterancesTheme="github-dark" # Default: github-dark
  utterancesIssueTerm="pathname" # Default: pathname

[params.meta]
  keywords = "Desarrollo web, programación, lenguajes de programación"
  description = "Sitio web con artículos sobre desarrollo web, lenguajes de programación y técnicas de programación."

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  hardWraps = true
  unsafe = true
  xHTML = true
[markup.highlight]
  codeFences = true
  lineNos = true
  lineNumbersInTable = true
  noClasses = false
  style = "monokai"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  group = "groups"
  tag = "tags"
  series = "series"
