[[main]]
  identifier = "home"
  name = "Inicio"
  url = "/"
  weight = 1

[[main]]
  identifier = "posts"
  name = "Artículos"
  url = "/posts"
  weight = 2

[[main]]
  identifier = "about"
  name = "Sobre mi"
  url = "/about"
  weight = 3
