[[main]]
  identifier = "posts"
  name = "Artículos"
  url = "posts"
  weight = 1

[[main]]
  identifier = "categories"
  name = "Categorías"
  url = "categories"
  weight = 2

[[main]]
  identifier = "tags"
  name = "Etiquetas"
  url = "tags"
  weight = 3

[[main]]
  identifier = "about"
  name = "Sobre mi"
  url = "about"
  weight = 4
