logoText = "WebDeveloper<hints/>" # Logo text that appears in the site navigation bar.
description = "Artículos sobre desarrollo de software" # for SEO
custom_css = [] # custom_css = ["scss/custom.scss"] and then make file at root/assets/scss/custom.scss
custom_js = [] # custom_js = ["js/custom.js"] and then make file at root/assets/js/custom.js

# header
homeHeaderType = "text" # text, img, slide

# navbar
enableThemeChange = true # site color theme

# body
enableBreadcrumb = true # breadcrumb for list, single page
enablePhotoSwipe = true # image viewer for gallery, single page
enableSearch = true # site search with Fuse
enableSearchHighlight = true # when true, search keyword will be highlighted
enableGoToTop = true # scroll to top
enableWhoami = true # at the end of single page
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2019" # "2006-01": group by month, "2006": group by year
archivePaginate = 13 # items per page
paginateWindow = 1 # setting it to 1 gives 7 buttons, 2 gives 9, etc. If set 1: [1 ... 4 5 6 ... 356] [1 2 3 4 5 ... 356] etc
talksGroupByDate = "2019" # "2006-01": group by month, "2006": group by year

# whoami: usage - home page sidebar, single page bottom of post. all values can be empty
myname = "Arturo López"
email = "arthurolg@gmail.com"
whoami = "Desarrollador de Software"
useGravatar = true
location = "Cancún, México"
organization = "arthurolg.com"
link = "https://arthurolg.com"

# sidebar
enableBio = true # home page sidebar
enableSidebar = true # Set to false to create the full width of the content.
enableSidebarTags = true # if you want to use tags.
enableSidebarSeries = true
enableSidebarCategories = true
enableToc = true # single page table of contents, you can replace this param to toc(toc = true)
hideToc = false # Hide or Show toc
enableTocSwitch = true # single page table of contents visibility switch
itemsPerCategory = 6 # maximum number of posts shown in the sidebar.

# footer
showPoweredBy = false # show footer text: Powered by Hugo and Zzo theme
showFeedLinks = true # RSS Feed
showSocialLinks = true # email, facebook, twitter ...
enableLangChange = false # show button at bottom left of footer.
themeOptions = ["dark", "hacker", "light", "solarized", "custom"] # select options for site color theme

# service
baiduAnalytics = "" # alternative of google analytics
enableBusuanzi = true # if set true, total page view, total unique visitors show up in the footer.
busuanziSiteUV = true # unique visitors (total number of visitors)
busuanziSitePV = true # site total page view count
busuanziPagePV = true # post view count

# comment
enableComment = true
disqus_shortname = "web-developer-hints"
commento = true

[utterances]       # https://utteranc.es/
owner = "lgzarturo"              # Your GitHub ID
repo = "webdeveloperhints"               # The repo to store comments

[socialOptions] # if set, social icons will show up.
email = "mailto:arthurolg@gmail.com"
facebook = "https://www.facebook.com/lgzarturo"
twitter = "https://twitter.com/lgzarturo"
github = "https://github.com/lgzarturo"
stack-overflow = ""
instagram = "https://www.instagram.com/lgzarturo/"
google-plus = ""
youtube = ""
medium = ""
tumblr = "https://arthurolg.tumblr.com/"
linkedin = "https://linkedin.com/in/lgzarturo"
pinterest = "https://www.pinterest.com.mx/arthurolg/"
stack-exchange = ""
telegram = "https://t.me/lgzarturo"
steam = "https://steamcommunity.com/id/arthurolg"
weibo = ""
douban = ""
csdn = ""
zhihu = ""
gitlab = "https://gitlab.com/lgzarturo"
mastodon = ""
jianshu = ""

[donationOptions]
enable = true # if set, the donation button will show up on the single page.
alipay = "" # Alipay QR Code image (example path: images/donation/alipay-qrcode.png) and put your file at root/static/images/donation/
wechat = "" # Wechat pay QR Code image (example path: same as above)
paypal = "https://paypal.me/arthurolg?locale.x=es_XC" # Paypal URL
patreon = "" # Patreon URL

[copyrightOptions]
enableCopyrightLink = true # if set, you can add copyright link
copyrightLink = "https://arthurolg.com"
copyrightLinkImage = ""
copyrightLinkText = ", Arturo López"
